name: Execução Diario do Robô

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
    - name : clonar repositorio
      uses : actions/checkout@v3

    - name: Commit do Relatorio
      run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain dados/relatorio.csv)" ]; then
            git add dados/relatorio.csv
            git commit -m "Atualização diaria"
            git push
          else
            echo "No changes detected in dados/relatorio.csv. Skipping commit."
          fi
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
